version: '3.8'
services:
  postgres-db:
    image: postgres:15-alpine
    container_name: pipeline_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: observability_db
    ports:
      - "5432:5432"
